[package]
name = "server"
version = "0.1.0"
edition = "2021"
authors = ["Andrea Monaco <andreamonaco2912@gmail.com>"]
description = "A server software that accepts connection of clients of the chat"
repository = "https://github.com/SqualoMenta/chat_multithread.git"

[dependencies]
